build:
	g++ --std=c++11 -o project2.out src/*.cpp




run:
	./project2.out out.tga input/testfile.tga
	./project.out part1.tga input/layer1.tga multiply input/pattern1.tga
	./project.out part2.tga input/car.tga subtract input/layer2.tga
	./project.out part3.tga input/layer1.tga multiply input/pattern2.tga screen input/text.tga
	./project.out part4.tga input/layer2.tga multiply input/circles.tga 
	./project.out part4.tga input/part4.tga subtract input/pattern2.tga
	./project.out part5.tga input/layer1.tga overlay input/pattern1.tga
	./project.out part6.tga input/car.tga addgreen 200
	./project.out part7.tga input/car.tga scalered 4 scaleblue 0
	./project.out part8_red.tga input/car.tga onlyred 
	./project.out part8_green.tga input/car.tga onlygreen
	./project.out part8_blue.tga input/car.tga onlyblue 
	./project.out part9.tga input/layer_blue.tga combine input/layer_green.tga input/layer_red.tga
	./project.out part10.tga input/text2.tga flip